### ISSUE TITLE
Design doc for editing engine 

### ISSUE THREAD

**Issue by ExecAssistNBNW** [nbnworg/issue-repo#10]
### Description 
Currently, we are displaying our articles in the format - Title -> Image -> n- paragraphs , which is prefixed in the eportal . As an editor , i should be able to display the article as per my requirement . 

![Image](https://github.com/user-attachments/assets/d9fa7ff6-a2a3-4f7f-9117-4a01413b2d28)

This  editing engine is to be designed in order to provide control to the editors in templates(the way in which we display articles) so that they can select and write in different formats . for ex- title ->image -> sub-title->paragraph . 

Functional requirements : 
* Should provide options to the editors to add Title , Images , Sub-titles , Lists , Paragraphs , references section , anchor links . 
* Should have option to add these things as per writer's preference 
* Should support Image and Text content

Note :  writer should be able to add things in multiple i.e. multiple paragraphs or images etc . Also , this editing engine is to be implemented in such a format that it can be used by both internal eportal and 3p eportal . 

Write a design document thoroughly comparing the ways in which it can be implemented , naming convention, folder structure, available api's to integrate etc .

**Requirements**
* Design document that discusses different mechanisms for implementation of editing engine
* Should have detailed comparisions, what's possible and whats not possible , best way to go with 

### Acceptance 
* reviewed by

**Comment by nbnw-org** [comment]
https://lavender-aftermath-c63.notion.site/Design-Document-for-Editing-Engine-cacbfa1fff4046ae8191b34b42e14e0a

**Comment by nbnw-org** [comment]
Marking this as complete. Will hand it over to developer.
