### ISSUE TITLE
[NBNW-Frontend] Feature article other chapters should be collapsed (Dummy Data)

### ISSUE THREAD

**Issue by nbnw-org** [nbnworg/issue-repo#112]

**Comment by nbnw-org** [comment]
Should this be marked as done? ya Abhi bhi review m hai???~

**Comment by hv65616** [comment]
As per the request by the tisha I have designed the feature article page that will be displaying the content of the feature articles. 
The data used while designing the page is Lorem Ipsum (Dummy Data)
Once approved content received by the tisha it will be updated

PS - Developement of the page is completed and ready to final deploy
