### ISSUE TITLE
Store rejected articles

### ISSUE THREAD

**Issue by ExecAssistNBNW** [nbnworg/issue-repo#14]
### Description
Currently when we are working on Editor Portal and when an editor rejects an article (or an admin rejects an article), the article is deleted from the database. We need ability to store the rejected articles and when rejecting, we should be asking a reason to the user due to which the editor/admin is rejecting the article which should be stored as well.

e.g. 
NewsModel {
id, contents, etc.
}

RejectedNewsModel{
...NewsModel,
rejection_reason,
rejectedBy
}

* rejection_reason is the reason for rejection
* rejectedBy is the userId of the individual who rejected the article.

### Requirements
* Rejected Articles should be stored in NBNWRejectedArticles table
* Rejected Articles should have the following extra parameters - rejection_reason, rejectedBy

### Acceptance Criteria
* Reviewed by - Pratyash

**Comment by ExecAssistNBNW** [comment]
Himanshu will review

**Comment by nbnw-org** [comment]
Someone will have to take this task up, putting it in backlog to be discussed in following standup.
