### ISSUE TITLE
[Doc] Write a detailed document on How to change categories and sub-categories

### ISSUE THREAD

**Issue by sarveshbhatnagar** [nbnworg/issue-repo#20]
### Description

Currently we had an issue where we had to change category from one category to another. Write a detailed document on how any individual can do the category migration.

### Requirement

We need to write a document that gives a detailed explanation about -

Updating Category

### Acceptance Criteria

* Reviewed by Sarvesh
* Reviewed by Tisha
* Demo'd to all (Live) by following document step by step
* Pushed to docs repository

**Comment by nbnw-org** [comment]
Example document to refer for update - https://github.com/nbnworg/docs/blob/main/development/deployment/ConfiguringDomains.md

**Comment by sarveshbhatnagar** [comment]
got confirmation from Tisha, she also validated the doc~
