### ISSUE TITLE
Code Refactoring- backend 

### ISSUE THREAD

**Issue by ExecAssistNBNW** [nbnworg/issue-repo#3]
### Description 

 As a developer , the current code creates issues if we are trying to implement a new thing . For ex - when there are any UI based changes , since there are alot of unnecessary divs and sections , it becomes difficult as it hinders the whole layout . Similarly , in backend , there are issues because of useEffect being rendered too many times . 
As a user as well, this creates issue in functioning of the website - takes alot of time to load etc . 
Therefore , the whole code needs to refactored .

**Requirements**  

1. the code base needs to be reviewed properly for identifying refactoring opportunities in nbnw website and editor portal  (backend) 
2. identify common elements that can be pulled over in common package 
3. identify common technical issues 

Note: Smithy model for both nbnw website and editor portal will be created by Sarvesh sir , APIs to be followed up according to that . 

You can refer to https://github.com/nbnworg/docs/blob/main/development/learning/codingPractices.md and try to find common issues , inconsistent file structuring , inconsistent variable names etc and work on fixing that . 

### Acceptance 

- identified and created a document for common issues 
- doc approved by Sarvesh and Tisha 
- fixed the issues and reviewed by Samarth (setsu) 

### Components involved 

nbnw-react-frontend, common package , nbnw-editor-final

**Comment by nbnw-org** [comment]
This is blocked until NextJs Migration.

**Comment by nbnw-org** [comment]
Krishna - Frontend and Himanshu - Backend

**Comment by sarveshbhatnagar** [comment]
@ExecAssistNBNW Need to separate the tasks.

**Comment by sarveshbhatnagar** [comment]
@hv65616 please feel free to create smaller sub tasks for this... Thanks!

**Comment by nbnw-org** [comment]
Closing this issue.
