### ISSUE TITLE
[3p-eportal] "Write Article" Page

### ISSUE THREAD

**Issue by nbnw-org** [nbnworg/issue-repo#33]
Need to create "Write Article" page as per figma UI

![Image](https://github.com/user-attachments/assets/f53e3373-5208-45d4-b700-9e2a95f0a3dd)

Note : this page requires "Submit Article" and "Save draft" API in the backend 

### Requirements 
* To create page as per UI

### Acceptance 
* reviewed by Meghna 
* reviewed by

**Comment by sarveshbhatnagar** [comment]
Check design document - https://lavender-aftermath-c63.notion.site/Design-Document-for-Editing-Engine-cacbfa1fff4046ae8191b34b42e14e0a .

We are using Editor.JS for creating editor portal. Use that to implement the UI, there are a lot of videos available for next js with editor.js ~
