### ISSUE TITLE
NextJS Migration Frontend

### ISSUE THREAD

**Issue by nbnw-org** [nbnworg/issue-repo#40]
### Description
* We want to convert website to nextjs so that we are able to render all the metadata at server side and get page SEO.

### Requirements
* NextJs Application Created
* Amplify Connected to NextJS
* Video Series watched
* All news metadata is rendered at Server side

### Acceptance Criteria
* Server Side rendering of metadata
* NextJS code is migrated

**Comment by saka015** [comment]
1.Home Page Done
2. Category Page left
4. Search Page left
5. Loader Issue

**Comment by nbnw-org** [comment]
Marking this as handover to Himanshu for completion while doing refactoring of code.
