### ISSUE TITLE
[API Model] Create API Model for NBNW frontend and Editor Portal.

### ISSUE THREAD

**Issue by sarveshbhatnagar** [nbnworg/issue-repo#44]
### Description
We need to create API Model for NBNW frontend before refactoring the backend api's for NBNW.

### Dependencies
NBNW Frontend website, Editor Portal.

### Acceptance Criteria
* Reviewed by Swanand

**Comment by nbnw-org** [comment]
Started with editor portal, since it is mostly similar to 3p eportal. PR - https://github.com/nbnworg/nbnw-editor-portal-model/pull/1

**Comment by sarveshbhatnagar** [comment]
NBNW Frontend Model - https://github.com/nbnworg/nbnw-frontend-model/pull/1

**Comment by nbnw-org** [comment]
Reviewed by Swanand, merging and closing this.
