### ISSUE TITLE
Back to top when clicked on NBNW Logo

### ISSUE THREAD

**Issue by ExecAssistNBNW** [nbnworg/issue-repo#48]
### Description 
The footer in the nbnw.org has our logo , it should have an ability of going back to top of the page which we are on- just to make it more user friendly . 

### Requirements 
back to top of whichever page we are on , when clicked 

### Acceptance 
* all requirements are fulfilled.
* reviewed by 

### Components affected 
nbnw-react-frontend

**Comment by nbnw-org** [comment]
rough estimate - 1
