### ISSUE TITLE
Code refactoring - frontend

### ISSUE THREAD

**Issue by ExecAssistNBNW** [nbnworg/issue-repo#50]
### Description
As a developer , the current code creates issues if we are trying to implement a new thing . For ex - when there are any UI based changes , since there are alot of unnecessary divs and sections , it becomes difficult as it hinders the whole layout . Similarly , in backend , there are issues because of useEffect being rendered too many times .
As a user as well, this creates issue in functioning of the website - takes alot of time to load etc .
Therefore , the whole code needs to refactored .

### Requirements

- the code base needs to be reviewed properly for identifying refactoring opportunities in nbnw website and editor portal (Frontend)
- identify common elements that can be pulled over in common package
- identify common technical issues
-Nextjs migration to be followed up simultaneously

Note: there are some common UI updates that need to be fixed :
* the website shouldn't be static - make it dynamic and it should look like the UI created by meghna 
* need to remove summary from article page 
* need to remove navbar buttons from every page
* pagination to be implemented 

You can refer to https://github.com/nbnworg/docs/blob/main/development/learning/codingPractices.md and try to find common issues , inconsistent file structuring , inconsistent variable names etc and work on fixing that .

### Acceptance

1. identified and created a document for common issues
2. doc approved by Sarvesh and Tisha
3. fixed the issues and reviewed by Samarth (setsu) and Sarvesh 
4.  approval by meghna 

### Components involved
nbnw-react-frontend, common package , nbnw-editor-final

**Comment by hv65616** [comment]
The fronted of NBNW is currently build on ReactJS now its high time to migrate it to the NextJS. It is required to imporve the SEO of our current website by creating a server side rendering website using next.js and also a fresh, clean and more appropiate code writing will be followed. There will be new UI followed for homepage, article page and soon.
Below i have created the granular task of how would i approach this to migrate the fronted from reactjs to nextjs

 - Amplify setup
 - Importing amplify functions that are responsible to fetch data from backend to frontend
 - Create Navbar, Search and Dropdown
 - Create Footer
 - Creating the Home page (it include several components in which the home page is divided so the entire home page with consiste of 10 sections according to the new UI)
 - Creation of article page
 - Importing the voting functionality
 - Creating of author page
