### ISSUE TITLE
Suggestions section and reloading ( page , suggestion section , latest section ) - Article page 

### ISSUE THREAD

**Issue by ExecAssistNBNW** [nbnworg/issue-repo#6]
### Description 
As a user , when you visit the article page and select on any suggested articles , there is in place change in the article i.e. the page doesn't reload upon selection and directly changes the content as per selection. Also , upon selection of some article from the suggestions column , the suggestions doesn't change i.e. it still shows the suggestions that were there earlier including the article that was selected . 

**Requirements**

1. reloading of the page after a new article is selected 
2. updated suggestions should appear after selection 

### Acceptance 

* both the issues are fixed 
* reviewed by Pratyash

### Components affected 

nbnw-react-frontend

**Comment by nbnw-org** [comment]
This was completed by Himanshu
