### ISSUE TITLE
[NBNW-Frontend] Latest Section Size issue when image doesn't load

### ISSUE THREAD

**Issue by nbnw-org** [nbnworg/issue-repo#85]
### Description
 
* As a nbnw user when I open nbnw news, sometimes when image doesn't load the latest section size becomes very small and stays small, I want it to be fixed to image length instead.

### AC
* Reviewed by Himanshu

**Comment by SwanandBhuskute** [comment]
Ok @nbnw-org, will fix this!

**Comment by SwanandBhuskute** [comment]
- latest section height issue fixed - used resizerObserver in js
- font sizes of many text components reduced for small screens
- footer made smaller for all screens
- author page articles - line after last article removed
