### ISSUE TITLE
Byline and Image attribution

### ISSUE THREAD

**Issue by ExecAssistNBNW** [nbnworg/issue-repo#9]
### Description 
Currently , the eportal-id , time , date of posting of the editors are being displayed at the end of the article which is not correct . Also , the images attribution is not visible beneath the image , but it is getting stored in the backend . 

**Requirements**
* the Byline should be visible after the title as per UI 
* the image attribution needs to be displayed as per UI 

Note : the name of the editor as well as the attribution are being stored so do refer to the table . 

### Acceptance 
* improvements are made as per requirements 
* Reviewed by Himanshu
* Reviewed by Meghna 

### Components involved
nbnw-react-frontend

**Comment by nbnw-org** [comment]
Any updates @SwanandBhuskute ? Thanks :)!

**Comment by SwanandBhuskute** [comment]
yes i asked for feedback in yesterday's standup, will raise the PR today
