### ISSUE TITLE
[NBNW-Frontend] Images ka size consistent hona chahiye

### ISSUE THREAD

**Issue by nbnw-org** [nbnworg/issue-repo#96]

**Comment by SwanandBhuskute** [comment]
- tried again to fix the size of images on home page and news page
- adjusted width of left section at 28%, this won't allow images to get too big
- adjusted titleAndSummary to 25%, don't know how it broke, but now fixed permanently
- on news page, now max-width of img is 100% and normal width will be auto, and img will be placed centered
